spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "qwerty"

  jpa:
    hibernate:
      ddl-auto: "create"